[package]
name = "pre-calc-v2"
version = "0.1.0"
authors = ["JDSeiler"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "pre-calc-v2"
path = "main.rs"
